services:
  app:
    build: .  # Build from the Dockerfile in the current directory
    container_name: smoobu-calender-sync
    volumes:
      - ./calendar-secrets.json:/app/secrets/calendar-secrets.json
      - ./token.pickle:/app/secrets/token.pickle
      - ./.setenv:/app/secrets/.setenv
      - smoobu-calender-data:/app/data
    restart: unless-stopped  # Restart policy

volumes:
  smoobu-calender-data:
